# Set the prefix to '`'
set -g prefix `
bind ` send-prefix

# True colors support
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides ",xterm-ghostty:Tc"

# Status bar settings
set -g status-style bg=default,fg="#bfbdb7",bright
set -g status-left ""
set -g status-right "#[fg=magenta]󱫋  #[fg="#bfbdb7",bright]#S"

set -g window-status-format "#W"
set -g window-status-current-format "#W"

set -g window-status-bell-style "bg=red,nobold"
set -g window-status-current-style \
	"#{?window_zoomed_flag,bg=yellow,bg=magenta,nobold}"

# Pane separators
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright

# Keybindings
bind | split-window -h
bind - split-window -v
bind f resize-pane -Z
